" vundle
set nocompatible
filetype off

" set the runtime path to include Vundle and init
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'

call vundle#end()
filetype plugin indent on
" ~vundle

syntax on
set number relativenumber
set autoindent
set smartindent
set cursorline
set ruler
set laststatus=2
set wrap textwidth=0 wrapmargin=0 linebreak
set tabstop=2 expandtab shiftwidth=2
set visualbell
set noerrorbells

" vim search
set incsearch
set nowrapscan
set hlsearch

let mapleader="\<tab>"

" noremap
noremap i k
noremap ; i
noremap j h
noremap k j
noremap q b

" noremap tabs
noremap <leader>n :tabnew<SPACE>
noremap <leader>j :tabprev<CR>
noremap <leader>l :tabnext<CR>
noremap <leader>i :tabfirst<CR>
noremap <leader>k :tablast<CR>
noremap <leader>x :q!<CR>
noremap <leader>s :wq<CR>
noremap <leader>q :q<CR>
noremap <leader>w :w<CR>
noremap <leader>1 1gt
noremap <leader>2 2gt
noremap <leader>3 3gt
noremap <leader>4 4gt
noremap <leader>5 5gt
noremap <leader>6 6gt
noremap <leader>7 7gt
noremap <leader>8 8gt
noremap <leader>9 9gt

" noremap NERDTree
noremap t1 :NERDTreeToggle<CR>

" different cursor shape in different modes
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
