#---------------------------- Workspace Popup ---------------------------------
# prefix + f: file picker popup -> add to vim buffers
# -T popup title not supported in tmux version being used.
bind -n F1 display-popup -E -w 80% -h 80% "$HOME/workspace/personal/dotfiles/tmux/tmux-workspace-file-picker.sh"
#---------------------------- Workspace Popup ---------------------------------
