#-------------------------------- keybindings ---------------------------------
source-file ~/workspace/personal/dotfiles/tmux/workman-keymap.tmux.conf
source-file ~/workspace/personal/dotfiles/tmux/function-bindings.tmux.conf
#-------------------------------- keybindings ---------------------------------

#----------------------------------- Misc -------------------------------------
# vi copy-mode
setw -g mode-keys vi

set -g default-terminal "tmux-256color"
set -g mouse on

# search settings
setw -g wrap-search off
#----------------------------------- Misc -------------------------------------

#---------------- https://github.com/tmux-plugins/tmux-sensible ---------------
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0
set -g history-limit 50000
# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000
# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5
# Emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs
# Focus events enabled for terminals that support them
set -g focus-events on
#---------------- https://github.com/tmux-plugins/tmux-sensible ---------------

#---------------------------------- Colors ------------------------------------
purple_calm="#8888C6"
peach_calm="#e06c75"
sky="#addadb"
grass_cool="#A5C261"
green_calm="#629755"
slate="#727575"
blue_gray="#60799a"
#---------------------------------- Colors ------------------------------------

#----------------------------- Windows and Panes ------------------------------
set -g base-index 1
set -g pane-base-index 1

# Automatically renumber window numbers on closing a pane
set -g renumber-windows on

# Dynamically update term tab and window titles.
set -g set-titles on

set -g pane-border-lines heavy
set -g pane-border-style "fg=${slate}"
set -g pane-active-border-style "fg=${blue_gray}"
#----------------------------- Windows and Panes ------------------------------

#----------------------------------- Status -----------------------------------
set -g status-position top
setw -g monitor-activity on
# setw -g monitor-silence 300

set -g status-justify centre

set -g status-style "fg=${purple_calm},bg=default"
set -g status-left-length 100
# alt glyph: 
set -g status-left "#[fg=${sky},bold] ▶◀ #S #[fg=${grass_cool},nobold]| "

set -g window-status-format "#I:#W#{?window_activity_flag,🚀,}#{?window_silence_flag,🤨,}#{?window_marked_flag,📌,}#{?window_bell_flag,🥁,}"
# When prefix is active, current window tab is red; otherwise normal
tmp="#{?client_prefix,${peach_calm},${grass_cool}}"
# window_bell_flag, window_activity_flag, window_silence_flag don't seem
# to affect curr window.
set -g window-status-current-format "#[fg=${tmp},bold] ▶ #[underscore]#I:#W#{?window_zoomed_flag,🔎︎,}#{?window_marked_flag,📌,}"

set -g status-right-length 100
set -g status-right "#[fg=${peach_calm},bg=default] #[fg=${peach_calm},bg=default] #(uptime | cut -f 4-5 -d ' ' | tr -d ',')  #[fg=${peach_calm},bg=default] %H%M:%d-%b "

set -g message-style "fg=default,bg=${green_calm}"
#----------------------------------- Status -----------------------------------
